server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: bootsecurity
    key-store-type: PKCS12
    key-alias: bootsecurity
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: bitc5600
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # 여기서 쿼리문다보여줌
    properties:
      hibernate.format_sql: true